from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from freecm.dependency_lock import (
    LOCK_SCHEMA_CONTRACT,
    load_dependency_lock_data,
    validate_dependency_lock_data,
)
from freecm.errors import FreeCMError, LockfileValidationError
from freecm.lock_schema import LOCK_SCHEMA_RESOURCE

REPO_ROOT = Path(__file__).resolve().parents[1]


class DependencyLockTests(unittest.TestCase):
    def _minimal_lock_data(self) -> dict[str, object]:
        return {
            "schemaVersion": 5,
            "depsMode": "pinned",
            "depsManualPath": {
                "LibA": "",
            },
            "dependencies": {
                "LibA": {
                    "repoName": "RepoA",
                    "remote": "https://example.invalid/repo-a.git",
                    "commit": "abc123",
                    "latestRef": "main",
                },
            },
        }

    def test_validate_dependency_lock_data_normalizes_optional_maps_and_repo_name(self) -> None:
        data = self._minimal_lock_data()
        data["AppConfigs"] = {"MARKETING_VERSION": "1.0.0", "DevMode": False}

        validated = validate_dependency_lock_data(
            data,
            path_label="source_roots.lock.jsonc",
            expected_dependency_names=("LibA",),
        )

        self.assertEqual(validated["cmakeEnvironment"], {})
        self.assertEqual(validated["cmakeCacheVariables"], {})
        self.assertEqual(validated["terminalPath"], {})
        self.assertEqual(validated["assets"], {})
        self.assertEqual(validated["AppConfigs"], {"MARKETING_VERSION": "1.0.0", "DevMode": False})
        self.assertEqual(validated["dependencies"]["LibA"]["repoName"], "RepoA")  # type: ignore[index]

    def test_validate_dependency_lock_data_ignores_legacy_abi_group(self) -> None:
        data = self._minimal_lock_data()
        data["dependencies"]["LibA"]["abiGroup"] = ""  # type: ignore[index]

        validated = validate_dependency_lock_data(
            data,
            path_label="source_roots.lock.jsonc",
            expected_dependency_names=("LibA",),
        )

        self.assertNotIn("abiGroup", validated["dependencies"]["LibA"])  # type: ignore[index]

    def test_validate_dependency_lock_data_rejects_legacy_swift_configs(self) -> None:
        data = self._minimal_lock_data()
        data["SwiftConfigs"] = {"MARKETING_VERSION": "1.0.0"}

        with self.assertRaisesRegex(ValueError, "SwiftConfigs is no longer supported"):
            validate_dependency_lock_data(
                data,
                path_label="source_roots.lock.jsonc",
                expected_dependency_names=("LibA",),
            )

    def test_validate_dependency_lock_data_rejects_top_level_dev_mode(self) -> None:
        data = self._minimal_lock_data()
        data["DevMode"] = False

        with self.assertRaisesRegex(ValueError, "DevMode is no longer supported"):
            validate_dependency_lock_data(
                data,
                path_label="source_roots.lock.jsonc",
                expected_dependency_names=("LibA",),
            )

    def test_load_dependency_lock_data_wraps_validation_errors(self) -> None:
        with tempfile.TemporaryDirectory() as tempdir:
            path = Path(tempdir) / "source_roots.lock.jsonc"
            data = self._minimal_lock_data()
            data["dependencies"]["LibA"]["repoName"] = "../RepoA"  # type: ignore[index]
            path.write_text(json.dumps(data), encoding="utf-8")

            with self.assertRaises(LockfileValidationError) as context:
                load_dependency_lock_data(path, expected_dependency_names=("LibA",))

        self.assertIsInstance(context.exception, FreeCMError)
        self.assertIsInstance(context.exception, ValueError)
        self.assertIn("repository name", str(context.exception))

    def test_lock_schema_contract_is_loaded_from_packaged_resource(self) -> None:
        self.assertEqual(
            LOCK_SCHEMA_CONTRACT["schemaVersion"], LOCK_SCHEMA_RESOURCE["schemaVersion"]
        )
        self.assertEqual(LOCK_SCHEMA_CONTRACT["modes"], tuple(LOCK_SCHEMA_RESOURCE["modes"]))
        self.assertEqual(
            LOCK_SCHEMA_CONTRACT["dependencyEntryFields"],
            tuple(LOCK_SCHEMA_RESOURCE["dependencyEntryFields"]),
        )
        self.assertEqual(
            LOCK_SCHEMA_CONTRACT["workspaceLockProtocol"],
            LOCK_SCHEMA_RESOURCE["workspaceLockProtocol"],
        )

    def test_generated_vscode_lock_schema_is_tracked(self) -> None:
        schema_path = REPO_ROOT / "vscode-extension" / "src" / "lockSchema.ts"
        schema_text = schema_path.read_text(encoding="utf-8")

        self.assertIn("Generated by scripts/write-lock-schema.mjs", schema_text)
        self.assertIn(f"LOCK_SCHEMA_VERSION = {LOCK_SCHEMA_CONTRACT['schemaVersion']}", schema_text)
        for field_value in LOCK_SCHEMA_CONTRACT["fields"].values():  # type: ignore[index,union-attr]
            self.assertIn(f'"{field_value}": "{field_value}"', schema_text)
        self.assertIn(
            f'ACTIVE_LOCK_NAME = "{LOCK_SCHEMA_CONTRACT["activeLockFileName"]}"',
            schema_text,
        )
        self.assertIn(
            f'TEMPLATE_LOCK_NAME = "{LOCK_SCHEMA_CONTRACT["templateLockFileName"]}"',
            schema_text,
        )
        self.assertIn(
            f'WORKSPACE_LOCK_NAME = "{LOCK_SCHEMA_CONTRACT["workspaceLockName"]}"',
            schema_text,
        )
        self.assertIn("workspaceLockProtocol: WORKSPACE_LOCK_PROTOCOL", schema_text)


class DependencyLockConformanceTests(unittest.TestCase):
    FIXTURE_ROOT = REPO_ROOT / "tests" / "fixtures" / "dependency-lock-conformance"

    def _projection(self, validated: dict[str, object]) -> dict[str, object]:
        dependencies: dict[str, dict[str, str]] = {}
        raw_dependencies = validated["dependencies"]
        assert isinstance(raw_dependencies, dict)
        for name in sorted(raw_dependencies):
            raw_entry = raw_dependencies[name]
            assert isinstance(raw_entry, dict)
            entry = {
                "remote": raw_entry["remote"],
                "commit": raw_entry["commit"],
            }
            for optional_field in ("repoName", "latestRef"):
                optional_value = raw_entry.get(optional_field)
                if optional_value is not None:
                    entry[optional_field] = optional_value
            dependencies[name] = entry
        raw_manual_paths = validated["depsManualPath"]
        assert isinstance(raw_manual_paths, dict)
        return {
            "schemaVersion": validated["schemaVersion"],
            "depsMode": validated["depsMode"],
            "depsManualPath": {name: raw_manual_paths[name] for name in sorted(raw_manual_paths)},
            "dependencies": dependencies,
        }

    def test_shared_lock_fixture_corpus(self) -> None:
        manifest = json.loads((self.FIXTURE_ROOT / "manifest.json").read_text(encoding="utf-8"))
        for fixture in manifest["cases"]:
            fixture_path = self.FIXTURE_ROOT / fixture["file"]
            with self.subTest(fixture=fixture["name"]):
                if not fixture["valid"]:
                    with self.assertRaises(ValueError):
                        load_dependency_lock_data(fixture_path)
                    continue

                validated = load_dependency_lock_data(fixture_path)
                projection = self._projection(validated)
                self.assertEqual(projection, fixture["expected"])
                if fixture.get("roundTrip"):
                    reparsed = validate_dependency_lock_data(
                        json.loads(json.dumps(projection)),
                        path_label=f"round-trip:{fixture['name']}",
                    )
                    self.assertEqual(self._projection(reparsed), fixture["expected"])


if __name__ == "__main__":
    unittest.main()
