// Generated by scripts/write-lock-schema.mjs from freecm/lock-schema-contract.json.
// Do not edit this file by hand; run npm run generate:lock-schema.

export const LOCK_SCHEMA_VERSION = 5;

export const DEPENDENCY_MODES = [
  "pinned",
  "latest",
  "manual"
] as const;

export type DependencyMode = (typeof DEPENDENCY_MODES)[number];

export const ACTIVE_LOCK_NAME = "source_roots.lock.jsonc";
export const TEMPLATE_LOCK_NAME = "source_roots.lock.jsonc.in";
export const WORKSPACE_LOCK_NAME = ".freecm.workspace.lock";
export const WORKSPACE_LOCK_PROTOCOL = {
  "schemaVersion": 1,
  "ownerFileName": "owner.json",
  "timeoutMs": 5000,
  "retryDelayMs": 50,
  "initializationGraceMs": 2000
} as const;
export const LEGACY_DEPENDENCY_ENTRY_FIELDS = [
  "abiGroup"
] as const;
export const DEPENDENCY_ENTRY_FIELDS = [
  "repoName",
  "remote",
  "commit",
  "latestRef"
] as const;
export const REQUIRED_DEPENDENCY_ENTRY_FIELDS = [
  "remote",
  "commit"
] as const;
export const OPTIONAL_DEPENDENCY_ENTRY_FIELDS = [
  "repoName",
  "latestRef"
] as const;
export const REMOVED_TOP_LEVEL_FIELDS = {
  "defaultMode": "depsMode",
  "manualRoots": "depsManualPath",
  "cmakeSettings": "cmakeEnvironment and cmakeCacheVariables",
  "assetSeeds": "assets",
  "assetDependencies": "assets",
  "buildSettings": "AppConfigs",
  "commercePolicy": "AppConfigs.commercePolicy",
  "DevMode": "AppConfigs.DevMode",
  "SwiftConfigs": "AppConfigs"
} as const;
export const SAFE_DEPENDENCY_NAME_PATTERN_SOURCE = "^[A-Za-z0-9][A-Za-z0-9_.-]*$";

export const LOCK_FIELDS = {
  "schemaVersion": "schemaVersion",
  "depsMode": "depsMode",
  "depsManualPath": "depsManualPath",
  "dependencies": "dependencies",
  "repoName": "repoName",
  "remote": "remote",
  "commit": "commit",
  "latestRef": "latestRef"
} as const;

export const LOCK_SCHEMA_CONTRACT = {
  schemaVersion: LOCK_SCHEMA_VERSION,
  modes: DEPENDENCY_MODES,
  activeLockFileName: ACTIVE_LOCK_NAME,
  templateLockFileName: TEMPLATE_LOCK_NAME,
  workspaceLockName: WORKSPACE_LOCK_NAME,
  workspaceLockProtocol: WORKSPACE_LOCK_PROTOCOL,
  legacyDependencyEntryFields: LEGACY_DEPENDENCY_ENTRY_FIELDS,
  dependencyEntryFields: DEPENDENCY_ENTRY_FIELDS,
  requiredDependencyEntryFields: REQUIRED_DEPENDENCY_ENTRY_FIELDS,
  optionalDependencyEntryFields: OPTIONAL_DEPENDENCY_ENTRY_FIELDS,
  removedTopLevelFields: REMOVED_TOP_LEVEL_FIELDS,
  safeDependencyNamePattern: SAFE_DEPENDENCY_NAME_PATTERN_SOURCE,
  fields: LOCK_FIELDS,
} as const;

const SAFE_DEPENDENCY_NAME_PATTERN = new RegExp(
  SAFE_DEPENDENCY_NAME_PATTERN_SOURCE,
);

export function dependencyMode(value: unknown): DependencyMode | undefined {
  return DEPENDENCY_MODES.find((mode) => mode === value);
}

export function isSafeDependencyName(name: string): boolean {
  return SAFE_DEPENDENCY_NAME_PATTERN.test(name);
}
